### ISSUE TITLE
Design non responsive sur téléphone

### ISSUE THREAD

**Issue by bagage** [opensolarmap/solfront#3]
En vrac :

- sur moto G (android), la barre du bas est tronquée :
![screenshot_2015-11-09-11-08-45](https://cloud.githubusercontent.com/assets/1451988/11057651/24ea7ffc-878d-11e5-84f4-41eca28dc926.png)
- sur iPhone 6 Plus, la barre du bas est trop grande : 
![screen shot 2015-11-10 at 09 27 32](https://cloud.githubusercontent.com/assets/1451988/11057671/48d85fc4-878d-11e5-8194-2e8666a1b2a8.png)
- le zoom par défaut est parfois trop faible, mais impossibilité de l'augmenter (cf screenshot iPhone 6)

**Comment by cquest** [comment]
Peux-tu tester cette version: http://opensolarmap.org/mobile.html ?

**Comment by bagage** [comment]
Chouette, une version mobile dédiée ! Par contre au niveau de l'affichage, ça déborde :
![screenshot_2015-11-12-18-29-21](https://cloud.githubusercontent.com/assets/1451988/11125832/40ea728a-896c-11e5-8be8-bb3e30ede9c3.png)

**Comment by cquest** [comment]
Nouvelle CSS mise en place, testée sur iPhone et tablette Android fullHD
