### ISSUE TITLE
Boutons : montrer qu'ils sont actionnables

### ISSUE THREAD

**Issue by CharlesNepote** [opensolarmap/solfront#5]
En attendant que je maîtrise mieux les branches dans git et que je t'envoie des pull request propres, voici une petite suggestion facile : créer la classe suivante pour mettre en exergue le fait que les icônes sont des boutons actionables (quand on passe la souris dessus, ils changent ainsi d'opacité) :
#orient svg:hover {
 		opacity: 1.0;
 	}
En n'oubliant de régler "opacity: 0.5;" dans #orient svg { }.

(Par ailleurs le style CSS des boutons SVG pourrait être refactorisé pour être plus faciles à styler/manipuler.)

**Comment by cquest** [comment]
Ajouté ! https://github.com/opensolarmap/solfront/commit/b705118d611d5714fb6aa77f7e5f38336acf896c
